spring.application.name=ERPSystem2025Nov27
spring.datasource.url=jdbc:postgresql://localhost:5432/erpsystem?currentSchema=customer
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
jwt.secret=erpsystemKey1234567890erpsystemKey1234567890
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.profiles.active=render

razorpay.key.id=tankRazorpayIntegrationKey
razorpay.key.secret=tankRazorpayIntegrationKeySecret

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=anilsonone@gmail.com
spring.mail.password=oigsysuhjmfzncpa
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

resend.api.key=re_cBhN81tw_

twilio.account.sid=${TWILIO_ACCOUNT_SID}
twilio.auth.token=${TWILIO_ACCOUNT_SID}
twilio.whatsapp.from=${TWILIO_WHATSAPP_FROM}

cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}

